### ISSUE TITLE
Support retention policy

### ISSUE THREAD

**Issue by edeandrea** [ishworkh/docker-image-artifact-upload#5]
The upload artifact job has the ability for a [retention policy](https://github.com/marketplace/actions/upload-a-build-artifact#retention-period). This would be really good to be able to specify here in this action.

**Comment by omonk** [comment]
@edeandrea have made a PR for this!

**Comment by ishworkh** [comment]
[PR](https://github.com/ishworkh/docker-image-artifact-upload/pull/8) was released.

**Comment by edeandrea** [comment]
Thank you!
