### ISSUE TITLE
Getting lots of warnings when using this action

### ISSUE THREAD

**Issue by edeandrea** [ishworkh/docker-image-artifact-upload#9]
Hi - great work with this action! I use it a lot!

I've started to notice lots of warnings though when using it:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Similar with your other action (https://github.com/ishworkh/docker-image-artifact-download)

**Comment by edeandrea** [comment]
Hi - just wanted to gently nudge this.

According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/, as of June 1 2023 your GitHub actions will no longer run if you do not make this change.

I'd love to continue using your 2 actions, but I am going to have to start investigating in other alternatives unfortunately.

**Comment by benlye** [comment]
Hopefully @ishworkh will release a new version with the latest @actions/core dependency package, but in the meantime I've published an updated versions myself. Feel free to use them:
`benlye/docker-image-artifact-upload@v1.2.1`
`benlye/docker-image-artifact-download@v1.2.1`

The only change I made was to update the Node dependencies and then build (with `ncc`) and release.

**Comment by edeandrea** [comment]
Thank you @benlye .

I'll give @ishworkh a bit more time to respond to this, but otherwise I will need to move away to something else (most likely what you've done).

**Comment by ishworkh** [comment]
Thank you very much for bringing my attention to this. The action has been updated/released. You should no longer see the deprecation warnings. If you continue to see them, plz let me know.

Closing this issue after https://github.com/ishworkh/docker-image-artifact-upload/pull/10

**Comment by edeandrea** [comment]
Thank you @ishworkh ! 

Is there anything I need to do to use the latest version? I don't see an updated version in the GitHub Marketplace (https://github.com/marketplace/actions/docker-image-artifact-download & https://github.com/marketplace/actions/docker-image-artifact-upload)

**Comment by ishworkh** [comment]
> Is there anything I need to do to use the latest version? I don't see an updated version in the GitHub Marketplace (https://github.com/marketplace/actions/docker-image-artifact-download & https://github.com/marketplace/actions/docker-image-artifact-upload)

No, no action needed from your side. The update was released in the same `v1` tag, so `ishworkh/docker-image-upload@v1` continue to work.

**Comment by benlye** [comment]
Works for me without warnings. Thanks.
